name: Build OpenWrt 24.10.1 with helloworld

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPENWRT_VERSION: v24.10.1
      FEED_HELLOWORLD: https://github.com/fw876/helloworld.git

    steps:
    - name: Checkout workflow repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential ccache libncurses5-dev zlib1g-dev gawk git gettext unzip file python3

    - name: Clone OpenWrt source
      run: |
        git clone --depth=1 --branch $OPENWRT_VERSION https://github.com/openwrt/openwrt.git openwrt

    - name: Add helloworld feed
      run: |
        echo "src-git helloworld $FEED_HELLOWORLD;main" >> openwrt/feeds.conf.default

    - name: Update and install feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Copy default config
      run: |
        cd openwrt
        # 使用官方默认配置为起点
        cp defconfig .config
        # 也可以使用下面指令生成默认config文件
        # make defconfig

    - name: Modify config to select luci-app-ssr-plus and helloworld packages
      run: |
        cd openwrt
        # 这里用脚本自动选择helloworld相关插件（例如luci-app-ssr-plus）
        scripts/feeds install -a
        # 通过修改.config勾选插件：
        echo "CONFIG_PACKAGE_luci-app-ssr-plus=y" >> .config
        echo "CONFIG_PACKAGE_ipt2socks=y" >> .config
        echo "CONFIG_PACKAGE_shadowsocks-libev-server=y" >> .config
        echo "CONFIG_PACKAGE_shadowsocks-libev-ss-redir=y" >> .config
        echo "CONFIG_PACKAGE_simple-obfs=y" >> .config
        # 生成完整配置
        make defconfig

    - name: Build firmware and packages
      run: |
        cd openwrt
        make -j$(nproc) V=s

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-build-artifacts
        path: openwrt/bin/


